### ISSUE TITLE
编译失败，报文件查找失败。确实没有date-fns文件夹

### ISSUE THREAD

**Issue by dashuaiit** [fanchaoo/netease-cloud-music-community#1]
文件查找失败：'date-fns/format' at main.js:6
文件查找失败：'date-fns/subDays' at main.js:7
ERROR  Build failed with errors.

**Comment by fanchaoo** [comment]
> 文件查找失败：'date-fns/format' at main.js:6
> 文件查找失败：'date-fns/subDays' at main.js:7
> ERROR Build failed with errors.

忘记写了，需要在前端项目根目录 npm install 一下

**Comment by Pepsi34** [comment]
手机上小程序登录半天 进不去是什么问题 电脑的没问题

**Comment by fanchaoo** [comment]
把这个去掉试试









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 下午5:24
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] 编译失败，报文件查找失败。确实没有date-fns文件夹 (#1)





 
手机上小程序登录半天 进不去是什么问题 电脑的没问题

**Comment by Pepsi34** [comment]
博主把哪个去掉 没看懂

**Comment by fanchaoo** [comment]
是手机预览有问题吗；要确认手机和电脑是在同一局域网内的；
hbuilder里manifest.json-&gt;微信小程序配置-&gt;检查安全域名和TLS版本





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上9:54
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] 编译失败，报文件查找失败。确实没有date-fns文件夹 (#1)





 
博主把哪个去掉 没看懂

**Comment by Pepsi34** [comment]
按照你说的弄了还是不行 主要是手机微信登录授权那里 按确定后一直处于正在登录状态 但是PC端可以登录进去

**Comment by fanchaoo** [comment]
点击小程序右上方三个点“...” -&gt; 点击开发调试 -&gt; 打开调试





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上10:55
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] 编译失败，报文件查找失败。确实没有date-fns文件夹 (#1)





 
按照你说的弄了还是不行 主要是手机微信登录授权那里 按确定后一直处于正在登录状态 但是PC端可以登录进去

**Comment by Pepsi34** [comment]
![image](https://user-images.githubusercontent.com/46698451/99987499-852fd100-2deb-11eb-80f8-5992371dc137.png)
![image](https://user-images.githubusercontent.com/46698451/99987580-9b3d9180-2deb-11eb-98d6-95dca174364f.png)
貌似控制台没什么问题
数据库连接那里我改成了jdbc:mysql://localhost:3306 跟你的80.70.7.76:30001不同 是否与这有关
还有我把mongodb的配置和依赖给删了

**Comment by gardenfff** [comment]
需要配置服务器吗，tomcat之类的，而且mpp中在enums中有一些说需要创建构建函数,是我idea问题还是项目问题？

**Comment by fanchaoo** [comment]
> 需要配置服务器吗，tomcat之类的，而且mpp中在enums中有一些说需要创建构建函数,是我idea问题还是项目问题？

不需要配置服务器，springboot项目直接main方法启动；
没有明白你说的mpp是什么，项目用到lombok了，需要安装插件；
