### ISSUE TITLE
App.vue中的domain中的地址

### ISSUE THREAD

**Issue by gardenfff** [fanchaoo/netease-cloud-music-community#4]
App.vue中的domain中的地址是怎么得到的？在后端中有配置吗

**Comment by fanchaoo** [comment]
就是后端项目启动之后的访问根路径

**Comment by Roses-and-Gold** [comment]
大佬你好！我按照你说的步骤把微信appid，数据库，oss等都配置好了，也编译通过了，但运行时一直在登录页面无法登陆上去，请问可能是什么问题呢，虚拟账号和密码需不需要修改呀，附上一张登录页面的图片
![image](https://user-images.githubusercontent.com/75869197/102160245-fad40d80-3e7c-11eb-83f2-7b07beffdd91.png)

**Comment by gardenfff** [comment]
> 大佬你好！我按照你说的步骤把微信appid，数据库，oss等都配置好了，也编译通过了，但运行时一直在登录页面无法登陆上去，请问可能是什么问题呢，虚拟账号和密码需不需要修改呀，附上一张登录页面的图片
> ![image](https://user-images.githubusercontent.com/75869197/102160245-fad40d80-3e7c-11eb-83f2-7b07beffdd91.png)

**Comment by gardenfff** [comment]
兄弟需要下载安装mongodb吗
报错Connection refused: connect

**Comment by fanchaoo** [comment]
暂时没用到mongo，可以移除相关配置，忽略也行，不影响运行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gardenfff"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 中午11:24
收件人: "fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;; 
抄送: "范超"<1104641801@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [fanchaoo/netease-cloud-music-community] App.vue中的domain中的地址 (#4)





 
兄弟需要下载安装mongodb吗
 报错Connection refused: connect
 
&mdash;

**Comment by fanchaoo** [comment]
是在电脑上运行的吗，还是在手机上运行的；
电脑上的话可以看下控制台，请求响应情况；
电脑端的话，前端的manifest.json有个检查安全域名和TLS的选项记得不要勾选






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 上午10:28
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] App.vue中的domain中的地址 (#4)





 
大佬你好！我按照你说的步骤把微信appid，数据库，oss等都配置好了，也编译通过了，但运行时一直在登录页面无法登陆上去，请问可能是什么问题呢，虚拟账号和密码需不需要修改呀，附上一张登录页面的图片

**Comment by gardenfff** [comment]
真的不需要修改mongodb吗，删除pom依赖与数据源后实体类也报错了
保留mongodb运行到：com.mongodb.MongoSocketOpenException: Exception opening socket 就开始报错，而且我看不出来项目地址，就是localhost：8081那个
![image](https://user-images.githubusercontent.com/57348713/102173364-cf314180-3ed5-11eb-891e-4fd668e0ad6b.png)

**Comment by gardenfff** [comment]
后端好像启动成功了。。。没有报错，但是那里看domin地址呢？

**Comment by fanchaoo** [comment]
properties文件里有port和context-path






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 中午1:32
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"范超"<1104641801@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [fanchaoo/netease-cloud-music-community] App.vue中的domain中的地址 (#4)





 
后端好像启动成功了。。。没有报错，但是那里看domin地址呢？
