### ISSUE TITLE
感谢大佬的帮忙，项目可以正常运行了

### ISSUE THREAD

**Issue by gardenfff** [fanchaoo/netease-cloud-music-community#6]
感谢大佬的帮忙，项目可以正常运行了，但是还有一些不懂得问题想请教：
1、导入的common子项目的用途是什么
2、在运行小程序的时候虽然能正常运行，但是图片、视频之类的是加载慢还是加载不出来，看不出，后端控制台没有报错，是因为使用你的oss问题吗

**Comment by fanchaoo** [comment]
common里放的是一些通用的东西，表实体，枚举啥的，当时想着写个管理后台，也能用这个；
图片视频慢估计是图片比较大






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanchaoo/netease-cloud-music-community"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:17
收件人:&nbsp;"fanchaoo/netease-cloud-music-community"<netease-cloud-music-community@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fanchaoo/netease-cloud-music-community] 感谢大佬的帮忙，项目可以正常运行了 (#6)





 
感谢大佬的帮忙，项目可以正常运行了，但是还有一些不懂得问题想请教：
 1、导入的common子项目的用途是什么
 2、在运行小程序的时候虽然能正常运行，但是图片、视频之类的是加载慢还是加载不出来，看不出，后端控制台没有报错，是因为使用你的oss问题吗

**Comment by gardenfff** [comment]
那么可以删除吗

**Comment by fanchaoo** [comment]
close
